# Generated by Django 2.0.3 on 2018-10-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Box_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
