# Generated by Django 2.0.3 on 2018-10-28 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Box_App', '0006_auto_20181028_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Contact_Box_App.Address'),
        ),
    ]
