# Generated by Django 2.0.3 on 2018-10-28 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Box_App', '0007_auto_20181028_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
